# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

---

version: 2.1
commands:
  install-node:
    steps:
      - run:
          name: Install Node.js
          command: |
            curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
            sudo apt-get install -y nodejs
parameters:
  python-version:
    type: string
    default: "3.13"
jobs:

  # via https://circleci.com/blog/deploying-documentation-to-github-pages-with-continuous-integration/
  publish:
    docker:
      - image: cimg/python:<< pipeline.parameters.python-version >>
    steps:
      - checkout
      - install-node
      - run:
          name: Install JavaScript dependencies
          command: npm --prefix ./glean install
      - run:
          name: NPM Authentication
          command: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > glean/.npmrc
      # This conditional matches the tag that contains 'pre', used
      # to mark prerelease builds. Since CircleCI conditionals do
      # not directly support 'else's, we need another conditional.
      - when:
          condition:
            matches:
              pattern: "^v.*-pre.*$"
              value: << pipeline.git.tag >>
          steps:
            - run:
                name: Publish to npm (prerelease)
                command: export PATH=.:$PATH && (cd glean && npm publish --access public --tag prerelease)
      # This conditional matches 'release': we won't tag the npm
      # release in this case, because no 'pre' is found in the tag.
      - when:
          condition:
            not:
              matches:
                pattern: "^v.*-pre.*$"
                value: << pipeline.git.tag >>
          steps:
            - run:
                name: Publish to npm
                command: export PATH=.:$PATH && (cd glean && npm publish --access public)
      - run:
          name: Get ghr release tool
          command: |
            GHR=ghr_v0.13.0_linux_amd64
            GHR_SHA256=c428627270ae26e206cb526cb8c7bdfba475dd278f6691ddaf863355adadfa13
            curl -sfSL --retry 5 -O "https://github.com/tcnksm/ghr/releases/download/v0.13.0/${GHR}.tar.gz"
            echo "${GHR_SHA256} *${GHR}.tar.gz" | sha256sum -c -
            tar -xf "${GHR}.tar.gz"
            cp ./${GHR}/ghr ghr

workflows:
  ci:
    jobs:
      - spellcheck
      - lint
      - build:
          requires:
            - lint
      - test:
          requires:
            - build
      - hold:
          type: approval
          requires:
            - lint
            - build
            - test
          filters:
            branches:
              ignore:
                - main
                - release
                - /^release-.*/
      - check-size:
          context: data-sre-gleanjs
          requires:
            - hold
      - browser-compat-smoke-tests:
          context: data-sre-gleanjs
          filters:
            branches:
              only:
                - main
                - release
                - /^release-.*/
      - docs-deploy:
          context: data-sre-gleanjs
          filters:
            branches:
              only:
                - main
                - release
                - /^release-.*/
      - publish:
          context: data-sre-gleanjs
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
