/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

import { DEFAULT_TELEMETRY_ENDPOINT } from "./constants";
import { validateURL } from "utils";

/**
 * Describes how to configure Glean.
 */
export interface ConfigurationInterface {
  // The build identifier generated by the CI system (e.g. "1234/A").
  readonly appBuild?: string,
  // The user visible version string fro the application running Glean.js.
  readonly appDisplayVersion?: string,
  // The server pings are sent to.
  readonly serverEndpoint?: string,
  // Whether or not Glean should be started in testing mode.
  readonly testing?: boolean
}

export class Configuration implements ConfigurationInterface {
  // The build identifier generated by the CI system (e.g. "1234/A").
  readonly appBuild?: string;
  // The user visible version string fro the application running Glean.js.
  readonly appDisplayVersion?: string;
  // The server pings are sent to.
  readonly serverEndpoint: string;
  // Whether or not Glean should be started in testing mode.
  readonly testing: boolean;

  constructor(config?: ConfigurationInterface) {
    this.appBuild = config?.appBuild;
    this.appDisplayVersion = config?.appDisplayVersion;
    this.testing = config?.testing || false;
    this.appBuild = config?.appBuild;

    if (config?.serverEndpoint && !validateURL(config.serverEndpoint)) {
      throw new Error(
        `Unable to initialize Glean, serverEndpoint ${config.serverEndpoint} is an invalid URL.`);
    }
    this.serverEndpoint = (config && config.serverEndpoint)
      ? config.serverEndpoint : DEFAULT_TELEMETRY_ENDPOINT;
  }
}
