---
name: Docs Deploy
on:
  push:
    branches:
      - release
jobs:
  docs-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: true
      - name: Node setup
        uses: actions/setup-node@v7
        with:
          node-version: 24
      - name: Install JS Dependencies
        run: npm --prefix ./documentation install
      - name: Build documentation
        run: npm --prefix ./documentation run build
      - name: Disable jekyll builds
        run: touch documentation/dist/.nojekyll
      - name: Show contents
        run: ls -R documentation/dist
      - name: Deploy with gh-pages
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npm --prefix ./documentation run publish:docs -- -u "dataops-ci-bot <dataops+ci-bot@mozilla.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
