---
name: Docs Deploy
on:
  push:
    branches:
      - main
      - release
      - /^release-.*/
jobs:
  docs-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Node setup
        uses: actions/setup-node@v7
        with:
          node-version: lts
      - name: Install JS Dependencies
        run: npm --prefix ./documentation install
#      - add_ssh_keys:
#          fingerprints:
#            - "ea:d2:3c:e1:09:cf:1a:1d:85:d6:6e:1d:52:0a:58:41"
      - name: Build documentation
        run: npm --prefix ./documentation run build
      - name: Disable jekyll builds
        run: touch documentation/dist/.nojekyll
      - name: Show contents
        run: ls -R documentation/dist
      - name: Setup SSH key and deploy docs to gh-pages branch
        run: |
          git config user.email "dataops+ci-bot@mozilla.com"
          git config user.name "dataops-ci-bot"
          npm --prefix ./documentation run publish:docs
